class Mutun {
  final String id;
  final String name;
  final String description;
  final String author;
  final List<String> sharhVideoUrls; // URLs to sharh videos
  final String pdfMatenUrl;
  final String pdfSharhUrl;
  final String bookTitle;
  final String bookAuthor;
  final String bookDescription;

  Mutun({
    required this.id,
    required this.name,
    required this.description,
    required this.author,
    required this.sharhVideoUrls,
    required this.pdfMatenUrl,
    required this.pdfSharhUrl,
    required this.bookTitle,
    required this.bookAuthor,
    required this.bookDescription,
  });
}

// List of all matns
final List<Mutun> allMatuns = [
  Mutun(
    id: '1',
    name: 'اختصر الأخضري',
    description: 'كتاب في الفقه المالكي يجمع بين الاختصار والشمول',
    author: 'الإمام أحمد الأخضري',
    sharhVideoUrls: ['https://example.com/video1', 'https://example.com/video2'],
    pdfMatenUrl: 'https://example.com/maten1.pdf',
    pdfSharhUrl: 'https://example.com/sharh1.pdf',
    bookTitle: 'شرح اختصر الأخضري',
    bookAuthor: 'العلماء المتخصصون',
    bookDescription: 'شرح مفصل وسهل الفهم لمتن الأخضري',
  ),
  Mutun(
    id: '2',
    name: 'المرشد المعين',
    description: 'متن في التجويد والقراءات',
    author: 'الإمام الشاطبي',
    sharhVideoUrls: ['https://example.com/video3'],
    pdfMatenUrl: 'https://example.com/maten2.pdf',
    pdfSharhUrl: 'https://example.com/sharh2.pdf',
    bookTitle: 'شرح المرشد المعين',
    bookAuthor: 'أحمد الشنقيطي',
    bookDescription: 'شرح جامع للمرشد المعين',
  ),
  Mutun(
    id: '3',
    name: 'بانت سعاد',
    description: 'قصيدة جاهلية مشهورة في النحو والصرف',
    author: 'قيس بن الملوح',
    sharhVideoUrls: ['https://example.com/video4', 'https://example.com/video5'],
    pdfMatenUrl: 'https://example.com/maten3.pdf',
    pdfSharhUrl: 'https://example.com/sharh3.pdf',
    bookTitle: 'شرح بانت سعاد',
    bookAuthor: 'الشيخ محمود',
    bookDescription: 'تحليل شامل لقصيدة بانت سعاد',
  ),
  Mutun(
    id: '4',
    name: 'الورقات',
    description: 'مقدمة في أصول الفقه',
    author: 'الإمام الجويني',
    sharhVideoUrls: ['https://example.com/video6'],
    pdfMatenUrl: 'https://example.com/maten4.pdf',
    pdfSharhUrl: 'https://example.com/sharh4.pdf',
    bookTitle: 'شرح الورقات',
    bookAuthor: 'الشيخ الشنقيطي',
    bookDescription: 'شرح مفيد لمتن الورقات',
  ),
  Mutun(
    id: '5',
    name: 'أصول مالك ابن أبي كف',
    description: 'متن في أصول الفقه المالكي',
    author: 'مالك ابن أبي كف',
    sharhVideoUrls: ['https://example.com/video7', 'https://example.com/video8'],
    pdfMatenUrl: 'https://example.com/maten5.pdf',
    pdfSharhUrl: 'https://example.com/sharh5.pdf',
    bookTitle: 'شرح أصول مالك',
    bookAuthor: 'العلماء المتخصصون',
    bookDescription: 'شرح تفصيلي لأصول الفقه',
  ),
  Mutun(
    id: '6',
    name: 'مطهرة القلوب',
    description: 'متن في السلوك والتزكية',
    author: 'الإمام الهروي',
    sharhVideoUrls: ['https://example.com/video9'],
    pdfMatenUrl: 'https://example.com/maten6.pdf',
    pdfSharhUrl: 'https://example.com/sharh6.pdf',
    bookTitle: 'شرح مطهرة القلوب',
    bookAuthor: 'الشيخ العلياني',
    bookDescription: 'شرح معمق للسلوك الإسلامي',
  ),
  Mutun(
    id: '7',
    name: 'عبيد ربه',
    description: 'متن في الآداب والسلوك',
    author: 'الإمام ابن المبارك',
    sharhVideoUrls: ['https://example.com/video10'],
    pdfMatenUrl: 'https://example.com/maten7.pdf',
    pdfSharhUrl: 'https://example.com/sharh7.pdf',
    bookTitle: 'شرح عبيد ربه',
    bookAuthor: 'الشيخ محمد',
    bookDescription: 'شرح شامل للآداب الإسلامية',
  ),
  Mutun(
    id: '8',
    name: 'أسهل المسالك',
    description: 'متن في النحو والصرف',
    author: 'الإمام ابن هشام',
    sharhVideoUrls: ['https://example.com/video11', 'https://example.com/video12'],
    pdfMatenUrl: 'https://example.com/maten8.pdf',
    pdfSharhUrl: 'https://example.com/sharh8.pdf',
    bookTitle: 'شرح أسهل المسالك',
    bookAuthor: 'عباس حسن',
    bookDescription: 'شرح شهير وسهل الفهم',
  ),
  Mutun(
    id: '9',
    name: 'الأرجوزة الميئية',
    description: 'أرجوزة في الحديث والتخريج',
    author: 'الإمام العراقي',
    sharhVideoUrls: ['https://example.com/video13'],
    pdfMatenUrl: 'https://example.com/maten9.pdf',
    pdfSharhUrl: 'https://example.com/sharh9.pdf',
    bookTitle: 'شرح الأرجوزة الميئية',
    bookAuthor: 'الشيخ الألباني',
    bookDescription: 'شرح علمي ودقيق',
  ),
  Mutun(
    id: '10',
    name: 'نصيحة حماد',
    description: 'متن في الحديث والفقه',
    author: 'حماد ابن أبي سليمان',
    sharhVideoUrls: ['https://example.com/video14'],
    pdfMatenUrl: 'https://example.com/maten10.pdf',
    pdfSharhUrl: 'https://example.com/sharh10.pdf',
    bookTitle: 'شرح نصيحة حماد',
    bookAuthor: 'الشيخ الفوزان',
    bookDescription: 'شرح مفيد وميسر',
  ),
  Mutun(
    id: '11',
    name: 'الطيبية',
    description: 'قصيدة في التجويد والقراءات',
    author: 'الإمام الشاطبي',
    sharhVideoUrls: ['https://example.com/video15', 'https://example.com/video16'],
    pdfMatenUrl: 'https://example.com/maten11.pdf',
    pdfSharhUrl: 'https://example.com/sharh11.pdf',
    bookTitle: 'شرح الطيبية',
    bookAuthor: 'محمود الطحان',
    bookDescription: 'شرح مفصل للقراءات',
  ),
  Mutun(
    id: '12',
    name: 'القلادة المكية',
    description: 'متن في التوحيد والعقيدة',
    author: 'الإمام القرافي',
    sharhVideoUrls: ['https://example.com/video17'],
    pdfMatenUrl: 'https://example.com/maten12.pdf',
    pdfSharhUrl: 'https://example.com/sharh12.pdf',
    bookTitle: 'شرح القلادة المكية',
    bookAuthor: 'عبدالرحمن الدوسري',
    bookDescription: 'شرح قيم في التوحيد',
  ),
  Mutun(
    id: '13',
    name: 'مقدمة الرسالة',
    description: 'مقدمة رسالة الإمام الشافعي',
    author: 'الإمام الشافعي',
    sharhVideoUrls: ['https://example.com/video18', 'https://example.com/video19'],
    pdfMatenUrl: 'https://example.com/maten13.pdf',
    pdfSharhUrl: 'https://example.com/sharh13.pdf',
    bookTitle: 'شرح مقدمة الرسالة',
    bookAuthor: 'محمد الخضري',
    bookDescription: 'شرح مهم في أصول الفقه',
  ),
];
