// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQXIuRdoFbLU4xhsqRzAL-VcLZ2xYjOBc',
    appId: '1:144144012452:web:968a5e6c21f58aee298231',
    messagingSenderId: '144144012452',
    projectId: 'miliana-hadirat-a190c',
    authDomain: 'miliana-hadirat-a190c.firebaseapp.com',
    storageBucket: 'miliana-hadirat-a190c.firebasestorage.app',
    measurementId: 'G-6ZGC8SZ8BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYJXjj_R3vsxJviBERNB1lmD_0UDCaQ1Q',
    appId: '1:144144012452:android:79527703cde3ef43298231',
    messagingSenderId: '144144012452',
    projectId: 'miliana-hadirat-a190c',
    storageBucket: 'miliana-hadirat-a190c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUQevp_JUyJo1XaLZWl4aYfHvv9RVUOpo',
    appId: '1:144144012452:ios:903e967d1e093ddb298231',
    messagingSenderId: '144144012452',
    projectId: 'miliana-hadirat-a190c',
    storageBucket: 'miliana-hadirat-a190c.firebasestorage.app',
    iosBundleId: 'com.example.milianaApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUQevp_JUyJo1XaLZWl4aYfHvv9RVUOpo',
    appId: '1:144144012452:ios:903e967d1e093ddb298231',
    messagingSenderId: '144144012452',
    projectId: 'miliana-hadirat-a190c',
    storageBucket: 'miliana-hadirat-a190c.firebasestorage.app',
    iosBundleId: 'com.example.milianaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQXIuRdoFbLU4xhsqRzAL-VcLZ2xYjOBc',
    appId: '1:144144012452:web:95c4c33654059cbd298231',
    messagingSenderId: '144144012452',
    projectId: 'miliana-hadirat-a190c',
    authDomain: 'miliana-hadirat-a190c.firebaseapp.com',
    storageBucket: 'miliana-hadirat-a190c.firebasestorage.app',
    measurementId: 'G-W0MLWPEQK0',
  );

}